apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "events"
  namespace: "default"
  labels:
    app: "events"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "events"
  template:
    metadata:
      labels:
        app: "events"
    spec:
      containers:
        - name: "events-sha256-1"
          image: "us-central1-docker.pkg.dev/yallanow-413400/yallanow-services/events-service:latest"
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_PASSWORD
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/google-credentials.json
            - name: AUTH_DNS
              value: "http://auth.default.svc.cluster.local/auth"
          volumeMounts:
            - name: google-credentials
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: google-credentials
          secret:
            secretName: google-credentials
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "events-hpa-oqd9"
  namespace: "default"
  labels:
    app: "events"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "events"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: events
  namespace: default
spec:
  selector:
    app: events
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
