apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "feed"
  namespace: "default"
  labels:
    app: "feed"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "feed"
  template:
    metadata:
      labels:
        app: "feed"
    spec:
      containers:
      - name: "feed-sha256-1"
        image: "us-central1-docker.pkg.dev/yallanow-413400/yallanow-services/feed-service:latest"
        env:
          - name: RECOMBEE_DATABASE_ID
            valueFrom:
              secretKeyRef:
                name: recombee-credentials
                key: RECOMBEE_DATABASE_ID
          - name: RECOMBEE_REGION
            valueFrom:
              secretKeyRef:
                name: recombee-credentials
                key: RECOMBEE_REGION
          - name: RECOMBEE_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: recombee-credentials
                key: RECOMBEE_SECRET_TOKEN
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/google-credentials.json
          - name: AUTH_DNS
            value: "http://auth.default.svc.cluster.local/auth"
        volumeMounts:
          - name: google-credentials
            mountPath: /var/secrets/google
            readOnly: true
      volumes:
        - name: google-credentials
          secret:
            secretName: google-credentials
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "feed-hpa-oqd9"
  namespace: "default"
  labels:
    app: "feed"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "feed"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: feed
  namespace: default
spec:
  selector:
    app: feed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
